### ISSUE TITLE
Crashes with unhelpful error message when using `send`

### ISSUE THREAD

**Issue by turion** [gyson/ex_type#18]
Consider the following minimal example:

```elixir
defmodule Foo do
  @spec foo(:foo) :: :bar
  def foo(:foo) do
    send(self(), "hello")
    :bar
  end
end
```

Type-checking it results in this error:

```
$ mix type
Compiling 1 file (.ex)
** (Protocol.UndefinedError) protocol ExType.Typespecable not implemented for %ExType.Type.Port{} of type ExType.Type.Port (a struct)
    lib/ex_type/typespecable.ex:5: ExType.Typespecable.impl_for!/1
    lib/ex_type/typespecable.ex:10: ExType.Typespecable.to_quote/1
    lib/ex_type/typespec.ex:908: ExType.Typespec.match_typespec/3
    lib/ex_type/typespec.ex:885: anonymous fn/4 in ExType.Typespec.match_typespec/3
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/ex_type/typespec.ex:883: ExType.Typespec.match_typespec/3
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/ex_type/typespec.ex:691: anonymous fn/2 in ExType.Typespec.eval_spec/3
```

If you want I can try and fix it in a PR.

**Comment by turion** [comment]
Removing the `send(self(), "hello")` line causes the error to disappear. The program executes correctly with and without the `send` statement.

**Comment by turion** [comment]
Strange, when I try this with a completely fresh project, it doesn't happen. Maybe I had an outdated version of `ex_type`? :thinking: Anyways, I'll close until I can reproduce again.
