### ISSUE TITLE
Crashes on new project

### ISSUE THREAD

**Issue by turion** [gyson/ex_type#20]
In order to more reliably test #18, I did the following simple steps:

* `mix new foo`
* `cd foo`
* Edit `mix.exs` so that it contains:
```
  defp deps do
    [
      {:ex_type, "~> 0.5.0"}
    ]
  end
```
* `mix type`

Error:

```elixir
$ mix type
Compiling 1 file (.ex)
Generated foo app
** (ArgumentError) argument error
    :erlang.length(nil)
    lib/ex_type/custom_env.ex:42: anonymous fn/1 in ExType.CustomEnv.BeforeCompile."MACRO-__before_compile__"/2
    (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    expanding macro: ExType.CustomEnv.BeforeCompile.__before_compile__/1
    lib/foo.ex:1: ExType.Module.Foo (module)
    (elixir 1.10.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
```

**Comment by turion** [comment]
The error persists after:

* changing `deps` to `{:ex_type, "~> 0.5.0", only: :dev}`
* adding a type spec to the `hello` function in the created project

**Comment by turion** [comment]
Ah. This is because the example project generated by `mix create` has a function `def hello`, and not `def hello()`. Therefore the argument list is `nil` instead of `[]`.

PR to fix this upcoming.

**Comment by turion** [comment]
The issue was #7 in the end.
