### ISSUE TITLE
Cannot use var as type variable

### ISSUE THREAD

**Issue by turion** [gyson/ex_type#25]
Consider this example:

```elixir
defmodule Foo do
  defstruct [:foo]
  @type t(foo) :: %__MODULE__{
    foo: foo
  }

  @spec get_foo(t(foo)) :: foo when foo: var
  def get_foo(%Foo{foo: foo}) do
    foo
  end
end
```

```
$ mix type
==> ex_type
Compiling 12 files (.ex)
warning: Code.ensure_compiled?/1 is deprecated. Use Code.ensure_compiled/1 instead (see the proper disclaimers in its docs)
  lib/ex_type/typespec.ex:831: ExType.Typespec.match_typespec/3

** (CaseClauseError) no case clause matching: {:error, {:not_found_type, Foo, :var, 0}}
    lib/ex_type/typespec.ex:616: ExType.Typespec.eval_type/2
    lib/ex_type/typespec.ex:657: anonymous fn/5 in ExType.Typespec.fetch_specs/3
    (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    lib/ex_type/typespec.ex:653: anonymous fn/4 in ExType.Typespec.fetch_specs/3
    (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    lib/ex_type/typespec.ex:648: ExType.Typespec.fetch_specs/3
    lib/ex_type/custom_env.ex:169: ExType.CustomEnv.process_defs/5
    (elixir 1.10.4) lib/enum.ex:1400: anonymous fn/3 in Enum.map/2
```

When I change the spec to `@spec get_foo(t(foo)) :: foo when foo: term()`, it works.

**Comment by turion** [comment]
See https://hexdocs.pm/elixir/typespecs.html#defining-a-specification where this usage is explained
