### ISSUE TITLE
Map update syntax causes error

### ISSUE THREAD

**Issue by turion** [gyson/ex_type#29]
Consider this example module:

```
defmodule Foo do
  @spec foo(t, map()) :: %{ :foo => t } when t: any()

  def foo(t, some_map) do
    %{some_map | foo: t}
  end
end
```

It causes this error:

```
$ mix type
** (CaseClauseError) no case clause matching: {%ExType.Context{}, %ExType.Type.List{type: %ExType.Type.Union{types: [%ExType.Type.TypedTuple{types: [%ExType.Type.Atom{literal: true, value: :foo}, %ExType.Type.Any{}]}, %ExType.Type.Map{key: %ExType.Type.Any{}, value: %ExType.Type.Any{}}]}}}
    lib/ex_type/checker.ex:37: ExType.Checker.eval/2
    lib/ex_type/typespec.ex:795: anonymous fn/3 in ExType.Typespec.match_typespec/3
    (elixir 1.10.4) lib/enum.ex:3343: Enum.flat_map_list/2
    lib/ex_type/typespec.ex:778: anonymous fn/4 in ExType.Typespec.match_typespec/3
    (elixir 1.10.4) lib/enum.ex:3343: Enum.flat_map_list/2
    lib/ex_type/typespec.ex:776: ExType.Typespec.match_typespec/3
    lib/ex_type/custom_env.ex:164: ExType.CustomEnv.process_defs/5
    (elixir 1.10.4) lib/enum.ex:1400: anonymous fn/3 in Enum.map/2
```

**Comment by turion** [comment]
The same error is caused by:

```
defmodule Foo do
  @spec foo(t, %{}) :: %{ :foo => t } when t: any()

  def foo(t, empty_map) do
    %{empty_map | foo: t}
  end
end
```

**Comment by turion** [comment]
It is _not_ caused by:

```elixir
defmodule Foo do
  defstruct []
  @spec foo(t, %{}) :: %{ :foo => t } when t: any()

  def foo(t, empty_map = %{}) do
    %{empty_map | foo: t}
  end
end
```

So probably the inferred type of `empty_map` is `map()` or `any()`, and this is unionised with `%{foo: t}`?

**Comment by turion** [comment]
Related error, even simpler:

```elixir
defmodule Foo do
  @spec foo(t) :: %{ :foo => t, :bar => t } when t: any()

  def foo(t) do
    %{foo: t, bar: t}
  end
end
```

```
** (CaseClauseError) no case clause matching: {%ExType.Context{}, %ExType.Type.List{type: %ExType.Type.Union{types: [%ExType.Type.TypedTuple{types: [%ExType.Type.Atom{literal: true, value: :bar}, %ExType.Type.Any{}]}, %ExType.Type.TypedTuple{types: [%ExType.Type.Atom{literal: true, value: :foo}, %ExType.Type.Any{}]}]}}}
    lib/ex_type/checker.ex:37: ExType.Checker.eval/2
    lib/ex_type/typespec.ex:795: anonymous fn/3 in ExType.Typespec.match_typespec/3
    (elixir 1.10.4) lib/enum.ex:3343: Enum.flat_map_list/2
    lib/ex_type/typespec.ex:778: anonymous fn/4 in ExType.Typespec.match_typespec/3
    (elixir 1.10.4) lib/enum.ex:3343: Enum.flat_map_list/2
    lib/ex_type/typespec.ex:776: ExType.Typespec.match_typespec/3
    lib/ex_type/custom_env.ex:164: ExType.CustomEnv.process_defs/5
    (elixir 1.10.4) lib/enum.ex:1400: anonymous fn/3 in Enum.map/2
```

**Comment by turion** [comment]
So currently, type inference is only done for `%{}` and `%{foo => bar}`. The missing cases are `%{some_map | foo => bar}` and `%{foo1 => bar1, foo2 => bar2,...}`.
